services:
  app:
    container_name: "app"
    build:
      context: ""
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html/
    networks:
      - app-network

  database:
    container_name: "database"
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: app-network-custom-driver